# Generated by Django 4.1 on 2022-09-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(db_index=True, default='any_name', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(db_index=True, default='any_name', max_length=200),
        ),
    ]
